### ISSUE TITLE
Change localhost to custom host and domain

### ISSUE THREAD

**Issue by micfio** [unavi-xyz/unavi#776]
Hello,how to change from localhost to hostname likes unavi.tech in order to set correctly the social login redirect uri .The server start Always in localhost:3000. I made change in .env file without result.
Also wich Is the http link and the port for start the Main Page in pnpm docker:prod? Thanks in advances

**Comment by kayhhh** [comment]
I've only deployed the client using a hosting provide like Vercel, so to be honest I'm not entirely sure of all the steps if you are running it with Docker (which it sounds like you are doing). `pnpm docker:prod` should start on `localhost:3000`. You can set `NEXT_PUBLIC_DEPLOYED_URL` in `.env` to your domain (ie I have it set to `https://unavi.xyz`), which will be used for a few things, one of which is the social login redirect url.
